php: 
  build: .
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./www:/var/www/html
  links:
   - db
   
db:
  image: mysql:5.7
  volumes:
   - /var/lib/mysql
  ports:
   - "5050:80"
  environment:
   - MYSQL_ROOT_PASSWORD=toor
   - MYSQL_DATABASE=mydb
  links:
   - phpmyadmin

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
     - ~/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
     - /custom/phpmyadmin/theme/:/www/themes/theme/